name: project_hmc
description: An Implementation Hybrid-Multiple Cryptosystem on the Flutter project.

publish_to: 'none'



environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  firebase_core: ^2.9.0
  firebase_core_web: ^2.3.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  flutter_screenutil: ^5.7.0
  flutter_otp_text_field: ^1.1.1
  country_calling_code_picker: ^2.0.1
  emoji_picker_flutter: ^1.5.2
  floating_action_bubble_custom: ^1.0.0+2
  anim_search_bar: ^2.0.3
  searchbar_animation: ^0.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
       - assets/
       - assets/chat_symbol.png
       - assets/whte.png

